services:
  bot:
    image: ${DOCKER_IMAGE:-yourusername/telegram-ai-assistant:latest}
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-telegram_bot}
    restart: unless-stopped
    depends_on:
      - redis
      - postgres
    networks:
      - bot-network

  redis:
    image: redis:6.2-alpine
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - bot-network

  postgres:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-telegram_bot}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - bot-network

volumes:
  redis-data:
  postgres-data:

networks:
  bot-network:
    driver: bridge