version: '3.8'

services:
  bot:
    # Keep all your existing bot service configuration
    build: .
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-telegram_bot}
    restart: unless-stopped
    depends_on:
      - redis
      - postgres
      - knowledge-base  # Add this dependency
    networks:
      - bot-network
    command: python run_bot.py

  # New service for knowledge base
  knowledge-base:
    build: ./knowledge-base
    volumes:
      - ./knowledge-base/data:/app/data
    restart: unless-stopped
    ports:
      - "5000:5000"
    networks:
      - bot-network

  # Keep your existing redis and postgres services
  redis:
    image: redis:6.2-alpine
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - bot-network

  postgres:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-telegram_bot}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - bot-network

volumes:
  redis-data:
  postgres-data:

networks:
  bot-network:
    driver: bridge